name: Python CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies (+ JAX cpu version)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      # Step 4: Run tests
      - name: Run tests with coverage
        run: |
          pytest -q \
            --maxfail=1 \
            --disable-warnings \
            --cov=src/pinet \
            --cov-branch \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml
      # Upload the XML as a build artifact so we (and Codecov) can inspect it
      - name: Upload coverage.xml artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          disable_search: true
          fail_ci_if_error: true
          verbose: true
